title: <p align="center"> Hugo Arellano </p>

logo: "/images/profile_hugo_arellano.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.whatsapp.com/?lang=en">Whatsapp</a> |
  <a href="https://github.com/hugoarellano">GitHub</a>
  </p>
  
  <p align="justify">
  I have a Bachelor degree in Economics from the University of Colima. I am passionate of the economy specially in the branches 
  that involve behavior, microeconomics, programming, technology and institucional efficiency. 
  </p>
  
  <p align="justify">
  I am able to use with a reasonable grade of effectiveness multiple python libraries
  oriented to solve different issues of the data science process, this alongside of the
  of general knowledge related to programming languages and software like microsoft excel,
  MySQL, Stata and R.
  </p>
  
theme: jekyll-theme-minimal
