title: <p align="center"> Hugo Arellano </p>

logo: "/images/carlos_hugo_arellano_profile.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume_en.pdf">Resume(en)</a> |
  <a href="pdf/resume_es.pdf">Resume(es)</a> |
  <a href="https://wa.me/message/6ZDKQHAIDXGGN1">Whatsapp</a> |
  <a href="https://github.com/hugoarellano">GitHub</a>
  </p>
  
  <p align="justify">
  I have a bachelor's degree in economics from the University of Colima. 
  I am passionate about the economy, especially in branches that involve 
  behavior, microeconomics, programming, technology, public policy,
  and institutional efficiency.
  </p>
  
theme: jekyll-theme-minimal
