title: <p align="center"> Hugo Arellano </p>

logo: "/images/profile_hugo_arellano.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.whatsapp.com/?lang=en">Whatsapp</a> |
  <a href="https://github.com/hugoarellano">GitHub</a>
  </p>
  
  <p align="justify">
  I consider myself as an inveterate learner and passionate of the economy, specially in the branches that involve behavior, microeconomics, 
  programming and technology.
  </p>
  
theme: jekyll-theme-minimal
