title: <p align="center"> Hugo Arellano </p>

logo: "/images/carlos_hugo_arellano_profile.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume(en)</a> |
  <a href="pdf/resume.pdf">Resume(es)</a> 
  <a href="https://www.whatsapp.com/?lang=en">Whatsapp</a> |
  <a href="https://github.com/hugoarellano">GitHub</a>
  </p>
  
  <p align="justify">
  I have a bachelor's degree in economics from the University of Colima. 
  I am passionate about the economy, especially in branches that involve 
  behavior, microeconomics, programming, technology, and institutional 
  efficiency. Furthermore, I am able to use with a reasonable grade of 
  effectiveness multiple python libraries oriented to solve different 
  issues of the data analysis process, alongside related tools and software
  like Microsoft Excel, MySQL, Stata, and R.
  </p>
  
theme: jekyll-theme-minimal
